version: '3.8'
services:
  db:
    image: postgres:16
    container_name: food_pg
    restart: always
    environment:
      POSTGRES_USER: fooduser
      POSTGRES_PASSWORD: foodpass
      POSTGRES_DB: fooddb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: