ingredients = {
    "fiber": "Фибри",
    "starch": "Нишесте",
    "sugars": "Захари",
    "galactose": "Галактоза",
    "glucose-dextrose": "Глюкоза",
    "sucrose": "Захароза",
    "lactose": "Лактоза",
    "maltose": "Малтоза",
    "fructose": "Фруктоза",
    "betaine": "Бетаин",
    "vitamin-a": "Витамин A",
    "vitamin-b1": "Витамин B1 (Тиамин)",
    "vitamin-b2": "Витамин B2 (Рибофлавин)",
    "vitamin-b3": "Витамин B3 (Ниацин)",
    "vitamin-b4": "Витамин B4 (Холин)",
    "vitamin-b5": "Витамин B5 (Пантотенова киселина)",
    "vitamin-b6": "Витамин B6 (Пиридоксин)",
    "vitamin-b9": "Витамин B9 (Фолиева киселина)",
    "vitamin-b12": "Витамин B12 (Кобалкамин)",
    "vitamin-c": "Витамин C",
    "vitamin-d": "Витамин D",
    "vitamin-e": "Витамин E",
    "vitamin-k1": "Витамин K1",
    "vitamin-k2-mk4": "Витамин K2 (MK04)",
    "alanine": "Аланин",
    "arginine": "Аргинин",
    "aspartic-acid": "Аспарагинова киселина",
    "valine": "Валин",
    "glycine": "Глицин",
    "glutamic-acid": "Глутамин",
    "isoleucine": "Изолевцин",
    "leucine": "Левцин",
    "lysine": "Лизин",
    "methionine": "Метионин",
    "proline": "Пролин",
    "serine": "Серин",
    "tyrosine": "Тирозин",
    "threonine": "Треонин",
    "tryptophan": "Триптофан",
    "phenylalanine": "Фенилаланин",
    "hydroxyproline": "Хидроксипролин",
    "histidine": "Хистидин",
    "cystine": "Цистин",
    "lipids": "Мазнини",
    "monounsaturated-acids": "Мононенаситени мазнини",
    "polyunsaturated-acids": "Полиненаситени мазнини",
    "saturated-acids": "Наситени мазнини",
    "trans-acids": "Трансмазнини",
    "iron": "Желязо",
    "potassium": "Калий",
    "calcium": "Калций",
    "magnesium": "Манезий",
    "manganese": "Манан",
    "copper": "Мед",
    "sodium": "Натрий",
    "selenium": "Селен",
    "fluoride": "Флуорид",
    "phosphorus": "Фосфор",
    "zinc": "Цинк",
    "cholesterol": "Холестерол",
    "phytosterols": "Фитостероли",
    "stigmasterol": "Стимастероли",
    "campesterol": "Кампестероли",
    "beta-sitosterol": "Бета-ситостероли",
    "alcohol-ethyl": "Алкохол",
    "water": "Вода",
    "caffeine": "Кофеин",
    "theobromine": "Теобромин",
    "ash": "Пепел",
}
